version: '3.1'

services:
  php-fpm:
    build: php
#    image: php:7.4-cli
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    user: "1000:1000"

  nginx:
    image: nginx
    volumes:
      - ../:/var/www/html
      - ./nginx/website.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - php-fpm
